### ISSUE TITLE
Light size settings don't seem to do anything

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#149]
Using latest Github version, Blender 2.76 and Renderman 20.3.  I tried altering the size X and Y settings in the lamp panel, but they seem to be broken.  The viewport size of the lamp will change with the 'X' parameter, but all sides scale the same, and the 'Y' parameter doesn't do anything.  As a result the area light always looks like a square.

In addition, neither of the size settings affect the actual light size in Renderman.  To do that you still have to manually scale the light.

**Comment by bsavery** [comment]
Fixed.

**Comment by jdent02** [comment]
Suggest reopening this one.  The 'Y' parameter still does nothing to the light shape (so it remains a square) and adjusting the 'X' parameter doesn't trigger an IT refresh (i.e. I have to stop and restart interactive mode to see any changes)

**Comment by bsavery** [comment]
Ah yeah they aren't tied in  to interactive rendering at the moment.

**Comment by bsavery** [comment]
So.  Interactive rendering is a tricky thing when it relates to adding or changing geometry.  We can add or delete lights (basically by setting the intensity to 0).  But you can't change the geometry on the fly.

So if for the shape/size change we wanted to do this we could do:
1.  Delete/hide the old light
2.  Make a new light with the new shape and a different name internally when rendering (this has to be done because otherwise the names overlap)

Issues with this are:  a:  light linking would then be broken as the names wouldn't match.
b:  If you were doing a ton of light shape editing you'd eventually end up with a ton of lights in the prman database behind the scene.

So I'm tempted to say this can't work for the time being with PRMan

**Comment by jdent02** [comment]
Crap, I keep forgetting that lights are geometry in PRMan (Cycles handles it's lighting a bit differently I think).  I agree that it would make more sense to just leave it as is and make some reference to it in the documentation.  I could just copy what you said verbatim as it makes sense.

BTW, the 'y' parameter on the rectangular area lights now affects the lamp in 3D view.  Not sure when that started working but it's great that it does.

**Comment by bsavery** [comment]
Oh and I think this is fixed anyway in 21.0 so yeah, no use worrying about now.

**Comment by jdent02** [comment]
What's fixed in 21.0?

**Comment by bsavery** [comment]
Light shapes.  Follows more what cycles does (except for mesh lights of course)
