### ISSUE TITLE
Sun Lamp direction is off

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#387]
https://renderman.pixar.com/forum/showthread.php?s=&threadid=33057

Probably flipped in X?

**Comment by jdent02** [comment]
I saw this issue too.  If I remember right I had to delete the light and make a new one then it worked properly.  Will test tonight.

**Comment by bsavery** [comment]
Really.  Was there IPR involved somehow?

**Comment by jdent02** [comment]
Both IPR and final render I think.  It was last week so I'm a bit fuzzy on it.  It was an existing file and it started showing the odd behavior when you added the X flip to the lights.

**Comment by bsavery** [comment]
Fixed in master branch.  For the life of me I can't figure how this happened.

**Comment by jdent02** [comment]
Bad news: still have issues.  Now it's 180 off on the Z axis
