### ISSUE TITLE
Deformation blur issue when mesh deformation is driven by something other than an armature

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#66]
Just summarizing the thread topic.

Deformation blur does not currently work when a mesh is deformed by something other than an armature (in this case a .mdd file).

**Comment by jdent02** [comment]
Would this be considered a bug?

**Comment by bsavery** [comment]
Yes. Haven't had a chance to get to this.

**Comment by jdent02** [comment]
No problem, just checking.

**Comment by bsavery** [comment]
I didn't get to test this with the recent changes, but they might have fixed this...

**Comment by jdent02** [comment]
I'll try it out this evening.

**Comment by jdent02** [comment]
nope, still no go on shape key driven deformation.

**Comment by jdent02** [comment]
Interesting development.........Deformation motion blur will work with vertex and cache based deformations.....so long as there's an armature modifier on the mesh.  Doesn't need to be an armature in the scene, but that appears to be what the exporter keys on to output deformation blur files.

Hope that helps.

**Comment by bsavery** [comment]
Excellent info. I can't take a look until after next week though. Siggraph!!!

**Comment by jdent02** [comment]
No worries.  The workaround is good enough for me and I'm sure there are more pressing issues.

I'm sure the exporter will get a lot of attention at Siggraph.  You've done a great job with it so far.

**Comment by bsavery** [comment]
I believe this was fixed?

**Comment by jdent02** [comment]
Mostly. Mesh cache modifier now blurs correctly but importing a cache as a series of shape keys still doesn't. What I mean by this is enabling the .mdd add on and then importing a .mdd file through that. It pulls the cache in and converts it to a shape key deformation, one key per frame.  This method does not produce blur still.  I'll whip up a small test file this evening and send you a link.

**Comment by jdent02** [comment]
File here:https://drive.google.com/file/d/0By1OtDH5oEWfdm1CSWg2RTZGUW8/view?usp=sharing
